### ISSUE TITLE
Please don't bundle etd

### ISSUE THREAD

**Issue by tarsius** [emacsfodder/kurecolor#17]
Please don't bundle your `etd.el`, or any other test helpers, in this repository, or any other. Bundling libraries that are also available separately is problematic because these copies tend to diverge over time. Users who install packages directly from git repositories (manually or using a third-party package manager that does that) will end up with two copies and it is undefined which ends up earlier on the `load-path`.

If it makes it much more convenient to bundle such tools in each repository that uses them, then please put them in a separate directory and add a file `.nosearch` in there to tell various tools that they should ignore the libraries in that directory.

Thanks!

**Comment by Trevoke** [comment]
Hi, I'm watching this repository because it looks like it might be valuable, and the lifecycle of this issue surprised me. Surely this can't have been closed on purpose. 

Tarsius is correct, this can lead to unexpected behavior on end users' emacsen and therefore is undesirable for your package.

At the very least, if `kurecolor` intends to stay on package repositories, it needs to be consistent with the expected experience of installing and using a package from that repository, otherwise it will damage that repository's reputation. On MELPA, the recipe is not attempting to filter these non-business-logic files out yet - https://github.com/melpa/melpa/blob/master/recipes/kurecolor

**Comment by jasonm23** [comment]
This issue is already open elsewhere

**Comment by tarsius** [comment]
> This issue is already open elsewhere

Sorry for opening a duplicate. Could you please point me to the other issue?

The only open issue in this repository is about something else and there are no open pull-requests. I also could not find an open issue about this in the Melpa repository and the pull-request that added this package does not mention `etd`. I am also not aware of another package that bundles `etd`. I couldn't find anything about it in `etd`'s own repository.

I would like to get this sorted out early on. If `etd` is a success and many people start using it, then this mistake is likely to propagate, which would considerably increase the effort to fix it eventually. Another testing tool made a similar mistake and I had to open close to a hundred (sic) pull-requests to fix that. I would rather not go through that again.

Do you disagree that it is a problem to bundle libraries? Or do you just think fixing this is not worth your time?

**Comment by jasonm23** [comment]
I appreciate your interest

If you wish to mitigate quickly I suggest you follow the three F laws of OSS.

It has been planned across multiple notes and issues and will be done in due course.

I would highly recommend closing the conversation as I have no time to look after this for a while.

**Comment by jasonm23** [comment]
#15 - this issue covers this.
